### ISSUE TITLE
how to use this repo on s7-414 PLC ?

### ISSUE THREAD

**Issue by forfuns** [mbuesch/raspi-profibus#3]
hi,I need connect PLC s7-414 with profibus read the running datas , and I try this repo , but I don't know how to use . pls help me , thanks !

**Comment by mbuesch** [comment]
I don't quite understand.
Do you want to run pyprofibus on the S7 PLC? That does not work.

**Comment by forfuns** [comment]
yes , I want to run `pyprofibus` on S7-414 PLC ,with `profibus` protocol to read and write PLC data , but I don't know how to use this code .

**Comment by mbuesch** [comment]
I'm sorry, that is not possible at all.

The S7 CPUs can only execute MC7 code. pyprofibus is written in Python (hence its name). There is no way this could (be made to) run on an S7 CPU.

Thanks for your interest in pyprofibus. Maybe you can still find another use for it.

**Comment by forfuns** [comment]
sorry , what I mean is that :
I want to write this code on my pi , and pi connected to S7 CPU with `profibus` . 
`pyprofibus` can do this ?

**Comment by mbuesch** [comment]
Ah, now I understand. You want to run pyprofibus as profibus slave.
And the answer is: Well, partially. The 'more-features' branch in the git repository should have partial support for that.
It is still work in progress and it will not work out of the box.

**Comment by forfuns** [comment]
OK. thanks , is helpful .
